COUNTRIES = dict([
    ('AF',('Afghanistan','Asia')),
    ('AL',('Albania','Europe')),
    ('DZ',('Algeria','Africa')),
    ('AD',('Andorra','Europe')),
    ('AO',('Angola','Africa')),
    ('AG',('Antigua and Barbuda','North America')),
    ('AR',('Argentina','South America')),
    ('AM',('Armenia','Europe')),
    ('AU',('Australia','Oceania')),
    ('AT',('Austria','Europe')),
    ('AZ',('Azerbaijan','Europe')),
    ('BS',('Bahamas','North America')),
    ('BH',('Bahrain','Asia')),
    ('BD',('Bangladesh','Asia')),
    ('BB',('Barbados','North America')),
    ('BY',('Belarus','Europe')),
    ('BE',('Belgium','Europe')),
    ('BZ',('Belize','North America')),
    ('BJ',('Benin','Africa')),
    ('BT',('Bhutan','Asia')),
    ('BO',('Bolivia','South America')),
    ('BA',('Bosnia and Herzegovina','Europe')),
    ('BW',('Botswana','Africa')),
    ('BR',('Brazil','South America')),
    ('BN',('Brunei','Asia')),
    ('BG',('Bulgaria','Europe')),
    ('BF',('Burkina Faso','Africa')),
    ('BI',('Burundi','Africa')),
    ('CV',('Cabo Verde','Africa')),
    ('KH',('Cambodia','Asia')),
    ('CM',('Cameroon','Africa')),
    ('CA',('Canada','North America')),
    ('CF',('Central African Republic','Africa')),
    ('TD',('Chad','Africa')),
    ('CL',('Chile','South America')),
    ('CN',('China','Asia')),
    ('CO',('Colombia','South America')),
    ('KM',('Comoros','Africa')),
    ('CG',('Congo','Africa')),
    ('CR',('Costa Rica','North America')),
    ('CI',('Côte d\'Ivoire','Africa')),
    ('HR',('Croatia','Europe')),
    ('CU',('Cuba','North America')),
    ('CY',('Cyprus','Europe')),
    ('CZ',('Czech Republic','Europe')),
    ('KP',('Democratic People\'s Republic of Korea','Asia')),
    ('CD',('Democratic Republic of the Congo','Africa')),
    ('DK',('Denmark','Europe')),
    ('DJ',('Djibouti','Africa')),
    ('DM',('Dominica','North America')),
    ('DO',('Dominican Republic','North America')),
    ('EC',('Ecuador','South America')),
    ('EG',('Egypt','Africa')),
    ('SV',('El Salvador','North America')),
    ('GQ',('Equatorial Guinea','Africa')),
    ('ER',('Eritrea','Africa')),
    ('EE',('Estonia','Europe')),
    ('SZ',('Eswatini','Africa')),
    ('ET',('Ethiopia','Africa')),
    ('FM',('Federated States of Micronesia','Oceania')),
    ('FJ',('Fiji','Oceania')),
    ('FI',('Finland','Europe')),
    ('FR',('France','Europe')),
    ('GA',('Gabon','Africa')),
    ('GM',('Gambia','Africa')),
    ('GE',('Georgia','Europe')),
    ('DE',('Germany','Europe')),
    ('GH',('Ghana','Africa')),
    ('GR',('Greece','Europe')),
    ('GD',('Grenada','North America')),
    ('GT',('Guatemala','North America')),
    ('GN',('Guinea','Africa')),
    ('GW',('Guinea Bissau','Africa')),
    ('GY',('Guyana','South America')),
    ('HT',('Haiti','North America')),
    ('HN',('Honduras','North America')),
    ('HK',('Hong Kong, China','Asia')),
    ('HU',('Hungary','Europe')),
    ('IS',('Iceland','Europe')),
    ('IN',('India','Asia')),
    ('ID',('Indonesia','Asia')),
    ('IR',('Iran','Asia')),
    ('IQ',('Iraq','Asia')),
    ('IE',('Ireland','Europe')),
    ('IL',('Israel','Europe')),
    ('IT',('Italy','Europe')),
    ('JM',('Jamaica','North America')),
    ('JP',('Japan','Asia')),
    ('JO',('Jordan','Asia')),
    ('KZ',('Kazakhstan','Asia')),
    ('KE',('Kenya','Africa')),
    ('KI',('Kiribati','Oceania')),
    ('KR',('Republic of Korea','Asia')),
    ('XK',('Kosovo','Europe')),
    ('KW',('Kuwait','Asia')),
    ('KG',('Kyrgyzstan','Asia')),
    ('LA',('Laos','Asia')),
    ('LV',('Latvia','Europe')),
    ('LB',('Lebanon','Asia')),
    ('LS',('Lesotho','Africa')),
    ('LR',('Liberia','Africa')),
    ('LY',('Libya','Africa')),
    ('LI',('Liechtenstein','Europe')),
    ('LT',('Lithuania','Europe')),
    ('LU',('Luxembourg','Europe')),
    ('MO',('Macau, China','Asia')),
    ('MG',('Madagascar','Africa')),
    ('MW',('Malawi','Africa')),
    ('MY',('Malaysia','Asia')),
    ('MV',('Maldives','Asia')),
    ('ML',('Mali','Africa')),
    ('MT',('Malta','Europe')),
    ('MH',('Marshall Islands','Oceania')),
    ('MR',('Mauritania','Africa')),
    ('MU',('Mauritius','Africa')),
    ('MX',('Mexico','North America')),
    ('MD',('Moldova','Europe')),
    ('MC',('Monaco','Europe')),
    ('MN',('Mongolia','Asia')),
    ('ME',('Montenegro','Europe')),
    ('MA',('Morocco','Africa')),
    ('MZ',('Mozambique','Africa')),
    ('MM',('Myanmar','Asia')),
    ('NA',('Namibia','Africa')),
    ('NR',('Nauru','Oceania')),
    ('NP',('Nepal','Asia')),
    ('NL',('Netherlands','Europe')),
    ('NZ',('New Zealand','Oceania')),
    ('NI',('Nicaragua','North America')),
    ('NE',('Niger','Africa')),
    ('NG',('Nigeria','Africa')),
    ('MK',('North Macedonia','Europe')),
    ('NO',('Norway','Europe')),
    ('OM',('Oman','Asia')),
    ('PK',('Pakistan','Asia')),
    ('PW',('Palau','Oceania')),
    ('PS',('Palestine','Asia')),
    ('PA',('Panama','North America')),
    ('PG',('Papua New Guinea','Oceania')),
    ('PY',('Paraguay','South America')),
    ('PE',('Peru','South America')),
    ('PH',('Philippines','Asia')),
    ('PL',('Poland','Europe')),
    ('PT',('Portugal','Europe')),
    ('QA',('Qatar','Asia')),
    ('RO',('Romania','Europe')),
    ('RU',('Russia','Europe')),
    ('RW',('Rwanda','Africa')),
    ('KN',('Saint Kitts and Nevis','North America')),
    ('LC',('Saint Lucia','North America')),
    ('VC',('Saint Vincent and the Grenadines','North America')),
    ('WS',('Samoa','Oceania')),
    ('SM',('San Marino','Europe')),
    ('ST',('São Tomé and Príncipe','Africa')),
    ('SA',('Saudi Arabia','Asia')),
    ('SN',('Senegal','Africa')),
    ('RS',('Serbia','Europe')),
    ('SC',('Seychelles','Africa')),
    ('SL',('Sierra Leone','Africa')),
    ('SG',('Singapore','Asia')),
    ('SK',('Slovakia','Europe')),
    ('SI',('Slovenia','Europe')),
    ('SB',('Solomon Islands','Oceania')),
    ('SO',('Somalia','Africa')),
    ('ZA',('South Africa','Africa')),
    ('SS',('South Sudan','Africa')),
    ('ES',('Spain','Europe')),
    ('LK',('Sri Lanka','Asia')),
    ('SD',('Sudan','Africa')),
    ('SR',('Suriname','South America')),
    ('SE',('Sweden','Europe')),
    ('CH',('Switzerland','Europe')),
    ('SY',('Syria','Asia')),
    ('TW',('Chinese Taipei','Asia')),
    ('TJ',('Tajikistan','Asia')),
    ('TZ',('Tanzania','Africa')),
    ('TH',('Thailand','Asia')),
    ('TL',('Timor-Leste','Asia')),
    ('TG',('Togo','Africa')),
    ('TO',('Tonga','Oceania')),
    ('TT',('Trinidad and Tobago','North America')),
    ('TN',('Tunisia','Africa')),
    ('TR',('Turkey','Europe')),
    ('TM',('Turkmenistan','Asia')),
    ('TV',('Tuvalu','Oceania')),
    ('UG',('Uganda','Africa')),
    ('UA',('Ukraine','Europe')),
    ('AE',('United Arab Emirates','Asia')),
    ('GB',('United Kingdom','Europe')),
    ('UY',('Uruguay','South America')),
    ('US',('United States','North America')),
    ('UZ',('Uzbekistan','Asia')),
    ('VU',('Vanuatu','Oceania')),
    ('VA',('Vatican City','Europe')),
    ('VE',('Venezuela','South America')),
    ('VN',('Vietnam','Asia')),
    ('YE',('Yemen','Asia')),
    ('ZM',('Zambia','Africa')),
    ('ZW',('Zimbabwe','Africa'))
])

CONTINENTS = ['Africa', 'Asia', 'Europe', 'North America', 'Oceania', 'South America']

SEPARATOR = '-----'
REGION_OPTIONS = ['World'] + [SEPARATOR] + CONTINENTS + [SEPARATOR] + [country[0] for country in COUNTRIES.values()]

DEFAULT_TIMETOWER_PARAMETERS = ['#000', '#555', '#444', '#999', 50, 60, 45, 30, 100, 500, 50, 100, 500, 'Helvetica 15 bold', 'Helvetica 15 bold', 'Helvetica 15', 'Helvetica 12 italic', 'Helvetica 15 bold', '#FFF', '#FFF', '#FFF', '#FFF', 50, 10, 16]